"""
Alertas de pedido/cadastro por RCA — painel de acompanhamento diário.

Só dois tipos ativos hoje: BNF SEM PEDIDO (aqui) e POSSÍVEL DUPLICIDADE
(calculada em Python — routers/alertas.py: compute_duplicidade_clusters(),
usando sql/duplicidade_raw_sql.py — porque precisa agrupar pedidos por
similaridade real, não só "cliente teve pedido duplicado").

Os demais tipos (erro de cadastro, pedido abaixo do mínimo, boleto com
prazo/plpag incorreto, liberado/bloqueado acumulado) foram desativados por
não fazerem sentido para o acompanhamento atual. Ficam comentados no final
do arquivo — reative descomentando e concatenando ao ALERTAS_EXTRAS caso
precise de novo.
"""

def build_alertas_sql() -> str:
    return """
WITH NOMES AS (
    SELECT
        CODUSUR,
        CODSUPERVISOR,
        NVL(
            SUBSTR(NOME, INSTR(NOME,' ')+1, INSTR(NOME,' ',INSTR(NOME,' ')+1)-INSTR(NOME,' ')-1),
            NOME
        ) AS NOME_CURTO
    FROM PONTUAL.PCUSUARI
)
SELECT DISTINCT
    A.CODCLI || '' AS CLIENTE,
    A.CODUSUR AS RCA,
    N.NOME_CURTO AS NOME,
    N.CODSUPERVISOR AS COD_SUPERVISOR,
    'BNF SEM PEDIDO' AS TIPO,
    (CASE A.POSICAO
        WHEN 'B' THEN 'BLOQUEADO' WHEN 'C' THEN 'CANCELADO'
        WHEN 'P' THEN 'PENDENTE'  WHEN 'M' THEN 'MONTADO'
        ELSE 'LIBERADO' END) AS STATUS_PEDIDO
FROM PONTUAL.PCPEDC A
LEFT JOIN NOMES N ON N.CODUSUR = A.CODUSUR
WHERE A.DATA BETWEEN SYSDATE-7 AND SYSDATE
  AND A.CONDVENDA IN (5,11)
  AND A.POSICAO NOT IN ('F','C')
  AND NOT EXISTS (
        SELECT 1 FROM PONTUAL.PCPEDC B
        WHERE B.DATA BETWEEN SYSDATE-7 AND SYSDATE
          AND B.CONDVENDA = 1
          AND B.CODCLI = A.CODCLI
      )
  AND A.CODCLI <> 11185
"""


# ─────────────────────────────────────────────────────────────────────────
# TIPOS DESATIVADOS — descomente e concatene ao SELECT acima (com UNION ALL
# antes de cada bloco) se precisar reativar algum. Todos usam a mesma CTE
# NOMES já definida no build_alertas_sql(); o bloco de LIBERADO/BLOQUEADO
# também precisa da CTE DIA_SEMANA (removida por não ser mais usada):
#
# DIA_SEMANA AS (
#     SELECT TRUNC(SYSDATE) - TRUNC(SYSDATE,'IW') + 1 AS DIA_ISO,
#            TO_CHAR(SYSDATE,'HH24:MI') AS HORA_ATUAL
#     FROM DUAL
# )
#
# UNION ALL
# SELECT DISTINCT
#     A.CODCLI || '' AS CLIENTE,
#     A.CODUSUR1 AS RCA,
#     N.NOME_CURTO AS NOME,
#     N.CODSUPERVISOR AS COD_SUPERVISOR,
#     'ERRO CADASTRO (UF)' AS TIPO,
#     NULL AS STATUS_PEDIDO
# FROM PONTUAL.PCCLIENT A
# LEFT JOIN NOMES N ON N.CODUSUR = A.CODUSUR1
# WHERE A.ESTENT IS NULL
#
# UNION ALL
# SELECT DISTINCT
#     A.CODCLI || '' AS CLIENTE,
#     A.CODUSUR AS RCA,
#     N.NOME_CURTO AS NOME,
#     N.CODSUPERVISOR AS COD_SUPERVISOR,
#     'PEDIDO ABAIXO DO MÍNIMO' AS TIPO,
#     (CASE A.POSICAO
#         WHEN 'B' THEN 'BLOQUEADO' WHEN 'C' THEN 'CANCELADO'
#         WHEN 'P' THEN 'PENDENTE'  WHEN 'M' THEN 'MONTADO'
#         ELSE 'LIBERADO' END) AS STATUS_PEDIDO
# FROM PONTUAL.PCPEDC A
# LEFT JOIN NOMES N ON N.CODUSUR = A.CODUSUR
# WHERE A.DATA > SYSDATE-7
#   AND A.CONDVENDA = 1
#   AND A.POSICAO NOT IN ('F','C','M')
#   AND A.VLATEND < 100
#
# UNION ALL
# SELECT DISTINCT
#     C.CODCLI || '' AS CLIENTE,
#     C.CODUSUR AS RCA,
#     N.NOME_CURTO AS NOME,
#     N.CODSUPERVISOR AS COD_SUPERVISOR,
#     'ERRO DE PRAZO NO BOLETO - ' || C.CODPLPAG AS TIPO,
#     (CASE C.POSICAO
#         WHEN 'B' THEN 'BLOQUEADO' WHEN 'C' THEN 'CANCELADO'
#         WHEN 'P' THEN 'PENDENTE'  WHEN 'M' THEN 'MONTADO'
#         ELSE 'LIBERADO' END) AS STATUS_PEDIDO
# FROM PONTUAL.PCPEDC C
# LEFT JOIN NOMES N ON N.CODUSUR = C.CODUSUR
# WHERE C.CODCOB = '7563'
#   AND C.CODPLPAG NOT IN (3,4,5,6,10,12,17,21,28,29,38,39,40,41,43,44,45,46,47,70)
#   AND C.POSICAO NOT IN ('F','C')
#   AND C.DATA > SYSDATE-7
#
# UNION ALL
# SELECT DISTINCT
#     C.CODCLI || '' AS CLIENTE,
#     C.CODUSUR AS RCA,
#     N.NOME_CURTO AS NOME,
#     N.CODSUPERVISOR AS COD_SUPERVISOR,
#     'ERRO DE PLPAG NA BNF' AS TIPO,
#     (CASE C.POSICAO
#         WHEN 'B' THEN 'BLOQUEADO' WHEN 'C' THEN 'CANCELADO'
#         WHEN 'P' THEN 'PENDENTE'  WHEN 'M' THEN 'MONTADO'
#         ELSE 'LIBERADO' END) AS STATUS_PEDIDO
# FROM PONTUAL.PCPEDC C
# LEFT JOIN NOMES N ON N.CODUSUR = C.CODUSUR
# WHERE C.CODCOB IN ('BNF','BNFT','BNFP')
#   AND C.CODPLPAG <> 8
#   AND C.POSICAO NOT IN ('F','C')
#
# UNION ALL
# SELECT
#     LIBERADOS.CLIENTE || '' AS CLIENTE,
#     LIBERADOS.RCA,
#     N.NOME_CURTO AS NOME,
#     N.CODSUPERVISOR AS COD_SUPERVISOR,
#     LIBERADOS.CONTAGEM || ' LIBERADO(S), ' || NVL(BLOQUEADOS.CONTAGEM,0) || ' BLOQUEADO(S)' AS TIPO,
#     NULL AS STATUS_PEDIDO
# FROM (
#     SELECT C.CODCLI AS CLIENTE, C.CODUSUR AS RCA, COUNT(DISTINCT C.NUMPED) AS CONTAGEM
#     FROM PONTUAL.PCPEDC C
#     WHERE C.DATA BETWEEN SYSDATE-7 AND SYSDATE AND C.POSICAO = 'L'
#     GROUP BY C.CODCLI, C.CODUSUR
# ) LIBERADOS
# LEFT JOIN (
#     SELECT B.CODCLI AS CLIENTE, B.CODUSUR AS RCA, COUNT(DISTINCT B.NUMPED) AS CONTAGEM
#     FROM PONTUAL.PCPEDC B
#     WHERE B.DATA BETWEEN SYSDATE-7 AND SYSDATE AND B.POSICAO IN ('P','B')
#     GROUP BY B.CODCLI, B.CODUSUR
# ) BLOQUEADOS ON LIBERADOS.CLIENTE = BLOQUEADOS.CLIENTE
# LEFT JOIN NOMES N ON N.CODUSUR = LIBERADOS.RCA
# CROSS JOIN DIA_SEMANA D
# WHERE BLOQUEADOS.CONTAGEM IS NOT NULL
#   AND (
#         (D.DIA_ISO BETWEEN 1 AND 4 AND D.HORA_ATUAL > '15:30')
#         OR (D.DIA_ISO = 5 AND D.HORA_ATUAL > '11:45')
#         OR (D.DIA_ISO IN (6,7))
#       )
#
# UNION ALL
# SELECT
#     P.CODCLI || '' AS CLIENTE,
#     P.CODUSUR1 AS RCA,
#     N.NOME_CURTO AS NOME,
#     N.CODSUPERVISOR AS COD_SUPERVISOR,
#     'ERRO CADASTRO (IE != ISENTO)' AS TIPO,
#     NULL AS STATUS_PEDIDO
# FROM PONTUAL.PCCLIENT P
# LEFT JOIN NOMES N ON N.CODUSUR = P.CODUSUR1
# WHERE P.TIPOFJ = 'F' AND P.IEENT <> 'ISENTO'
#
# UNION ALL
# SELECT
#     P.CODCLI || '' AS CLIENTE,
#     P.CODUSUR1 AS RCA,
#     N.NOME_CURTO AS NOME,
#     N.CODSUPERVISOR AS COD_SUPERVISOR,
#     'ERRO CADASTRO (CONTRIBUINTE)' AS TIPO,
#     NULL AS STATUS_PEDIDO
# FROM PONTUAL.PCCLIENT P
# LEFT JOIN NOMES N ON N.CODUSUR = P.CODUSUR1
# WHERE P.TIPOFJ = 'F' AND P.CONTRIBUINTE <> 'N'
#   AND P.CODUSUR1 NOT IN (2,10,50,160,180)
#
# UNION ALL
# SELECT
#     P.CODCLI || '' AS CLIENTE,
#     P.CODUSUR1 AS RCA,
#     N.NOME_CURTO AS NOME,
#     N.CODSUPERVISOR AS COD_SUPERVISOR,
#     'ERRO CADASTRO (CONSUMIDOR)' AS TIPO,
#     NULL AS STATUS_PEDIDO
# FROM PONTUAL.PCCLIENT P
# LEFT JOIN NOMES N ON N.CODUSUR = P.CODUSUR1
# WHERE P.TIPOFJ = 'F' AND P.CONSUMIDORFINAL <> 'S'
#   AND P.CODUSUR1 NOT IN (2,10,50,160,180)