"""
SQL do módulo de Faturamento (baseado na Rotina 1464 do Winthor).

O placeholder {DATE_REF} é substituído via str.replace() ANTES do .format(),
porque a data é uma string controlada pelo servidor (parse_data garante isso).
Os demais placeholders {excl_usur}, {filtro_*}, {select_final} são resolvidos
pelo .format() com kwargs nomeados.
"""
from typing import Optional
from config import FILIAL

# ─────────────────────────────────────────────────────────────────────────────
# SQL base com 8 CTEs
# ─────────────────────────────────────────────────────────────────────────────
BASE_SQL = """
WITH PARAMS AS (
    SELECT
        ADD_MONTHS(TRUNC(TO_DATE('{DATE_REF}','YYYY-MM-DD'),'MM'),-2)  AS DT_INI,
        TRUNC(TO_DATE('{DATE_REF}','YYYY-MM-DD'),'MM') - 1             AS DT_FIM,
        TRUNC(TO_DATE('{DATE_REF}','YYYY-MM-DD'),'MM')                 AS DT_MES_INI,
        LAST_DAY(TO_DATE('{DATE_REF}','YYYY-MM-DD'))                   AS DT_MES_FIM,
        TRUNC(TO_DATE('{DATE_REF}','YYYY-MM-DD')) - 1                  AS DT_ONTEM,
        TRUNC(TO_DATE('{DATE_REF}','YYYY-MM-DD'))                      AS DT_HOJE,
        TRUNC(TO_DATE('{DATE_REF}','YYYY-MM-DD'),'DAY')                AS DT_SEMANA_INI,
        (SELECT COUNT(*) FROM PCDATAS
          WHERE DATA BETWEEN ADD_MONTHS(TRUNC(TO_DATE('{DATE_REF}','YYYY-MM-DD'),'MM'),-2)
                         AND TRUNC(TO_DATE('{DATE_REF}','YYYY-MM-DD'),'MM')-1
            AND DIAUTIL = 'S')                                         AS DIAS_UTEIS_CONSULTA,
        (SELECT COUNT(*) FROM PCDATAS
          WHERE DATA BETWEEN TRUNC(TO_DATE('{DATE_REF}','YYYY-MM-DD'),'MM')
                         AND LAST_DAY(TO_DATE('{DATE_REF}','YYYY-MM-DD'))
            AND DIAUTIL = 'S')                                         AS DIAS_UTEIS_MES_ATUAL,
        (SELECT COUNT(*) FROM PCDATAS
          WHERE DATA BETWEEN TRUNC(TO_DATE('{DATE_REF}','YYYY-MM-DD'),'MM')
                         AND TRUNC(TO_DATE('{DATE_REF}','YYYY-MM-DD'))
            AND DIAUTIL = 'S') - 1                                     AS DIAS_UTEIS_DECORRIDOS
    FROM DUAL
),
VENDAS AS (
    SELECT
        PCUSUARI.CODUSUR                                                AS COD_VENDEDOR,
        PCUSUARI.NOME                                                   AS NOME_VENDEDOR,
        NVL(PCNFSAID.CODSUPERVISOR, PCSUPERV.CODSUPERVISOR)             AS COD_SUPERVISOR,
        PCSUPERV.NOME                                                   AS NOME_SUPERVISOR,
        PCSECAO.CODSEC                                                  AS COD_SECAO,
        PCSECAO.DESCRICAO                                               AS SECAO,
        SUM(
          CASE
            WHEN NVL(PCMOVCOMPLE.VLSUBTOTITEM,0) <> 0 THEN
                DECODE(NVL(PCMOV.TIPOITEM,'N'), 'I', 0,
                       NVL(PCMOVCOMPLE.VLSUBTOTITEM,0)
                       + (DECODE(NVL(PCMOV.TIPOITEM,'N'),'I',NVL(PCMOV.QTCONT,0),0)
                          * NVL(PCMOV.VLFRETE,0)))
            ELSE
                ROUND(
                  DECODE(PCMOV.CODOPER,
                         'S', NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0),
                         'ST',NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0),
                         'SM',NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0),0)
                  * NVL(DECODE(PCNFSAID.CONDVENDA, 7,
                       NVL(PCMOV.PUNITCONT,0)-NVL(PCMOV.VLIPI,0)-(NVL(PCMOV.ST,0)+NVL(PCMOVCOMPLE.VLSTTRANSFCD,0))+NVL(PCMOV.VLFRETE,0)+NVL(PCMOV.VLOUTRASDESP,0)+NVL(PCMOV.VLFRETE_RATEIO,0)+DECODE(NVL(PCNFSAID.SOMAREPASSEOUTRASDESPNF,'N'),'N',NVL(PCMOV.VLOUTROS,0),'S',NVL(PCMOV.VLOUTROS,0)-NVL(PCMOV.VLREPASSE,0)),
                       NVL(PCMOV.PUNIT,0)-NVL(PCMOV.VLIPI,0)-(NVL(PCMOV.ST,0)+NVL(PCMOVCOMPLE.VLSTTRANSFCD,0))+NVL(PCMOV.VLFRETE,0)+NVL(PCMOV.VLOUTRASDESP,0)+NVL(PCMOV.VLFRETE_RATEIO,0)+DECODE(NVL(PCNFSAID.SOMAREPASSEOUTRASDESPNF,'N'),'N',NVL(PCMOV.VLOUTROS,0),'S',NVL(PCMOV.VLOUTROS,0)-NVL(PCMOV.VLREPASSE,0))
                  ),0),2)
                + ROUND(NVL(PCMOV.QT,0)*DECODE(PCNFSAID.CONDVENDA,5,0,6,0,11,0,12,0,DECODE(PCMOV.CODOPER,'SB',0,NVL(PCMOV.ST,0)+NVL(PCMOVCOMPLE.VLSTTRANSFCD,0))),2)
                + ROUND(NVL(PCMOV.QT,0)*DECODE(PCNFSAID.CONDVENDA,5,0,6,0,11,0,12,0,DECODE(PCMOV.CODOPER,'SB',0,NVL(PCMOV.VLIPI,0))),2)
          END
        ) AS VLVENDA
    FROM PCNFSAID
        INNER JOIN PCMOV       ON PCMOV.NUMTRANSVENDA  = PCNFSAID.NUMTRANSVENDA AND PCMOV.CODFILIAL = PCNFSAID.CODFILIAL
        LEFT  JOIN PCMOVCOMPLE ON PCMOVCOMPLE.NUMTRANSITEM = PCMOV.NUMTRANSITEM
        INNER JOIN PCPRODUT    ON PCPRODUT.CODPROD     = PCMOV.CODPROD
        INNER JOIN PCUSUARI    ON PCUSUARI.CODUSUR     = PCNFSAID.CODUSUR
        INNER JOIN PCSUPERV    ON PCSUPERV.CODSUPERVISOR = NVL(PCNFSAID.CODSUPERVISOR,PCUSUARI.CODSUPERVISOR)
        LEFT  JOIN PCSECAO     ON PCSECAO.CODSEC       = PCPRODUT.CODSEC
        CROSS JOIN PARAMS P
    WHERE PCMOV.DTMOV      BETWEEN P.DT_INI AND P.DT_FIM
      AND PCNFSAID.DTSAIDA BETWEEN P.DT_INI AND P.DT_FIM
      AND PCMOV.CODFILIAL IN ('{FILIAL}') AND PCNFSAID.CODFILIAL IN ('{FILIAL}')
      AND PCMOV.CODOPER NOT IN ('SR','SO')
      AND NVL(PCNFSAID.TIPOVENDA,'X') NOT IN ('SR','DF')
      AND PCNFSAID.CODFISCAL NOT IN (522,622,722,532,632,732)
      AND PCNFSAID.CONDVENDA NOT IN (4,8,10,13,20,98,99)
      AND PCNFSAID.DTCANCEL IS NULL
      {excl_usur}
      {filtro_vendas}
    GROUP BY PCUSUARI.CODUSUR, PCUSUARI.NOME,
             NVL(PCNFSAID.CODSUPERVISOR,PCSUPERV.CODSUPERVISOR), PCSUPERV.NOME,
             PCSECAO.CODSEC, PCSECAO.DESCRICAO
),
DEVOLUCOES AS (
    SELECT PCNFENT.CODUSURDEVOL AS COD_VENDEDOR, PCSECAO.CODSEC AS COD_SECAO,
        SUM(CASE WHEN NVL(PCMOVCOMPLE.VLSUBTOTITEM,0)<>0 THEN
                NVL(PCMOVCOMPLE.VLSUBTOTITEM,0)
                -ROUND(NVL(PCMOV.QT,0)*DECODE(PCNFSAID.CONDVENDA,5,0,6,0,11,0,12,0,DECODE(PCMOV.CODOPER,'SB',0,NVL(PCMOV.VLIPI,0))),2)
                -ROUND(NVL(PCMOV.QT,0)*DECODE(PCNFSAID.CONDVENDA,5,0,6,0,11,0,12,0,DECODE(PCMOV.CODOPER,'SB',0,NVL(PCMOV.ST,0))),2)
            ELSE
                DECODE(PCNFSAID.CONDVENDA,5,0,DECODE(NVL(PCMOVCOMPLE.BONIFIC,'N'),'N',NVL(PCMOV.QT,0),0))
                *DECODE(PCNFSAID.CONDVENDA,5,0,6,0,11,0,
                        DECODE(PCMOV.PUNIT,0,NVL(PCMOV.PUNITCONT,0),NULL,NVL(PCMOV.PUNITCONT,0),NVL(PCMOV.PUNIT,0))
                        +NVL(PCMOV.VLFRETE,0)+NVL(PCMOV.VLOUTRASDESP,0)+NVL(PCMOV.VLFRETE_RATEIO,0)
                        -DECODE(NVL(PCNFSAID.SOMAREPASSEOUTRASDESPNF,'N'),'N',DECODE(NVL(PCMOV.VLOUTROS,0),0,NVL(PCMOV.VLREPASSE,0),0),'S',NVL(PCMOV.VLREPASSE,0))
                        +NVL(PCMOV.VLOUTROS,0))
        END) AS VLDEVOLUCAO
    FROM PCNFENT
        INNER JOIN PCESTCOM    ON PCESTCOM.NUMTRANSENT   = PCNFENT.NUMTRANSENT
        INNER JOIN PCMOV       ON PCMOV.NUMTRANSENT      = PCESTCOM.NUMTRANSENT AND PCMOV.CODFILIAL = PCNFENT.CODFILIAL
        LEFT  JOIN PCNFSAID    ON PCNFSAID.NUMTRANSVENDA = PCESTCOM.NUMTRANSVENDA
        LEFT  JOIN PCUSUARI    ON PCUSUARI.CODUSUR       = PCNFENT.CODUSURDEVOL
        INNER JOIN PCSUPERV    ON PCSUPERV.CODSUPERVISOR = NVL(PCNFSAID.CODSUPERVISOR,PCUSUARI.CODSUPERVISOR)
        LEFT  JOIN PCMOVCOMPLE ON PCMOVCOMPLE.NUMTRANSITEM = PCMOV.NUMTRANSITEM
        INNER JOIN PCPRODUT    ON PCPRODUT.CODPROD       = PCMOV.CODPROD
        INNER JOIN PCSECAO     ON PCSECAO.CODSEC         = PCPRODUT.CODSEC
        INNER JOIN PCCLIENT    ON PCCLIENT.CODCLI        = PCNFENT.CODFORNEC
        INNER JOIN PCPRACA     ON PCPRACA.CODPRACA       = PCCLIENT.CODPRACA
        CROSS JOIN PARAMS P
    WHERE PCNFENT.DTENT BETWEEN P.DT_INI AND P.DT_FIM
      AND PCMOV.DTMOV   BETWEEN P.DT_INI AND P.DT_FIM
      AND PCNFENT.CODFILIAL IN ('{FILIAL}') AND PCMOV.CODFILIAL IN ('{FILIAL}')
      AND NVL(PCNFENT.CODFISCAL,0) IN (131,132,231,232,199,299)
      AND PCMOV.CODOPER = 'ED'
      AND PCNFENT.TIPODESCARGA IN ('6','7','T')
      AND NVL(PCNFENT.TIPOMOVGARANTIA,-1)=-1
      AND NVL(PCNFENT.OBS,'X')<>'NF CANCELADA'
      AND PCMOV.DTCANCEL IS NULL
      AND NVL(PCNFSAID.CONDVENDA,0) NOT IN (4,8,10,13,20,98,99)
      {excl_devol}
      {filtro_devolucoes}
    GROUP BY PCNFENT.CODUSURDEVOL, PCSECAO.CODSEC
),
VENDAS_MES AS (
    SELECT PCUSUARI.CODUSUR AS COD_VENDEDOR, PCSECAO.CODSEC AS COD_SECAO,
        SUM(CASE WHEN NVL(PCMOVCOMPLE.VLSUBTOTITEM,0)<>0 THEN
                DECODE(NVL(PCMOV.TIPOITEM,'N'),'I',0,NVL(PCMOVCOMPLE.VLSUBTOTITEM,0)+(DECODE(NVL(PCMOV.TIPOITEM,'N'),'I',NVL(PCMOV.QTCONT,0),0)*NVL(PCMOV.VLFRETE,0)))
            ELSE
                ROUND(DECODE(PCMOV.CODOPER,'S',NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0),'ST',NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0),'SM',NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0),0)
                *NVL(DECODE(PCNFSAID.CONDVENDA,7,
                    NVL(PCMOV.PUNITCONT,0)-NVL(PCMOV.VLIPI,0)-(NVL(PCMOV.ST,0)+NVL(PCMOVCOMPLE.VLSTTRANSFCD,0))+NVL(PCMOV.VLFRETE,0)+NVL(PCMOV.VLOUTRASDESP,0)+NVL(PCMOV.VLFRETE_RATEIO,0)+DECODE(NVL(PCNFSAID.SOMAREPASSEOUTRASDESPNF,'N'),'N',NVL(PCMOV.VLOUTROS,0),'S',NVL(PCMOV.VLOUTROS,0)-NVL(PCMOV.VLREPASSE,0)),
                    NVL(PCMOV.PUNIT,0)-NVL(PCMOV.VLIPI,0)-(NVL(PCMOV.ST,0)+NVL(PCMOVCOMPLE.VLSTTRANSFCD,0))+NVL(PCMOV.VLFRETE,0)+NVL(PCMOV.VLOUTRASDESP,0)+NVL(PCMOV.VLFRETE_RATEIO,0)+DECODE(NVL(PCNFSAID.SOMAREPASSEOUTRASDESPNF,'N'),'N',NVL(PCMOV.VLOUTROS,0),'S',NVL(PCMOV.VLOUTROS,0)-NVL(PCMOV.VLREPASSE,0))
                ),0),2)
                +ROUND(NVL(PCMOV.QT,0)*DECODE(PCNFSAID.CONDVENDA,5,0,6,0,11,0,12,0,DECODE(PCMOV.CODOPER,'SB',0,NVL(PCMOV.ST,0)+NVL(PCMOVCOMPLE.VLSTTRANSFCD,0))),2)
                +ROUND(NVL(PCMOV.QT,0)*DECODE(PCNFSAID.CONDVENDA,5,0,6,0,11,0,12,0,DECODE(PCMOV.CODOPER,'SB',0,NVL(PCMOV.VLIPI,0))),2)
        END) AS VLVENDA_MES
    FROM PCNFSAID
        INNER JOIN PCMOV       ON PCMOV.NUMTRANSVENDA=PCNFSAID.NUMTRANSVENDA AND PCMOV.CODFILIAL=PCNFSAID.CODFILIAL
        LEFT  JOIN PCMOVCOMPLE ON PCMOVCOMPLE.NUMTRANSITEM=PCMOV.NUMTRANSITEM
        INNER JOIN PCPRODUT    ON PCPRODUT.CODPROD=PCMOV.CODPROD
        INNER JOIN PCUSUARI    ON PCUSUARI.CODUSUR=PCNFSAID.CODUSUR
        INNER JOIN PCSUPERV    ON PCSUPERV.CODSUPERVISOR=NVL(PCNFSAID.CODSUPERVISOR,PCUSUARI.CODSUPERVISOR)
        LEFT  JOIN PCSECAO     ON PCSECAO.CODSEC=PCPRODUT.CODSEC
        CROSS JOIN PARAMS P
    WHERE PCMOV.DTMOV      BETWEEN P.DT_MES_INI AND P.DT_HOJE
      AND PCNFSAID.DTSAIDA BETWEEN P.DT_MES_INI AND P.DT_HOJE
      AND PCMOV.CODFILIAL IN ('{FILIAL}') AND PCNFSAID.CODFILIAL IN ('{FILIAL}')
      AND PCMOV.CODOPER NOT IN ('SR','SO')
      AND NVL(PCNFSAID.TIPOVENDA,'X') NOT IN ('SR','DF')
      AND PCNFSAID.CODFISCAL NOT IN (522,622,722,532,632,732)
      AND PCNFSAID.CONDVENDA NOT IN (4,8,10,13,20,98,99)
      AND PCNFSAID.DTCANCEL IS NULL
      {excl_usur}
      {filtro_vendas_mes}
    GROUP BY PCUSUARI.CODUSUR, PCSECAO.CODSEC
),
DEVOLUCOES_MES AS (
    SELECT PCNFENT.CODUSURDEVOL AS COD_VENDEDOR, PCSECAO.CODSEC AS COD_SECAO,
        SUM(CASE WHEN NVL(PCMOVCOMPLE.VLSUBTOTITEM,0)<>0 THEN
                NVL(PCMOVCOMPLE.VLSUBTOTITEM,0)-ROUND(NVL(PCMOV.QT,0)*DECODE(PCNFSAID.CONDVENDA,5,0,6,0,11,0,12,0,DECODE(PCMOV.CODOPER,'SB',0,NVL(PCMOV.VLIPI,0))),2)-ROUND(NVL(PCMOV.QT,0)*DECODE(PCNFSAID.CONDVENDA,5,0,6,0,11,0,12,0,DECODE(PCMOV.CODOPER,'SB',0,NVL(PCMOV.ST,0))),2)
            ELSE
                DECODE(PCNFSAID.CONDVENDA,5,0,DECODE(NVL(PCMOVCOMPLE.BONIFIC,'N'),'N',NVL(PCMOV.QT,0),0))
                *DECODE(PCNFSAID.CONDVENDA,5,0,6,0,11,0,DECODE(PCMOV.PUNIT,0,NVL(PCMOV.PUNITCONT,0),NULL,NVL(PCMOV.PUNITCONT,0),NVL(PCMOV.PUNIT,0))+NVL(PCMOV.VLFRETE,0)+NVL(PCMOV.VLOUTRASDESP,0)+NVL(PCMOV.VLFRETE_RATEIO,0)-DECODE(NVL(PCNFSAID.SOMAREPASSEOUTRASDESPNF,'N'),'N',DECODE(NVL(PCMOV.VLOUTROS,0),0,NVL(PCMOV.VLREPASSE,0),0),'S',NVL(PCMOV.VLREPASSE,0))+NVL(PCMOV.VLOUTROS,0))
        END) AS VLDEVOLUCAO_MES
    FROM PCNFENT
        INNER JOIN PCESTCOM    ON PCESTCOM.NUMTRANSENT=PCNFENT.NUMTRANSENT
        INNER JOIN PCMOV       ON PCMOV.NUMTRANSENT=PCESTCOM.NUMTRANSENT AND PCMOV.CODFILIAL=PCNFENT.CODFILIAL
        LEFT  JOIN PCNFSAID    ON PCNFSAID.NUMTRANSVENDA=PCESTCOM.NUMTRANSVENDA
        LEFT  JOIN PCUSUARI    ON PCUSUARI.CODUSUR=PCNFENT.CODUSURDEVOL
        INNER JOIN PCSUPERV    ON PCSUPERV.CODSUPERVISOR=NVL(PCNFSAID.CODSUPERVISOR,PCUSUARI.CODSUPERVISOR)
        LEFT  JOIN PCMOVCOMPLE ON PCMOVCOMPLE.NUMTRANSITEM=PCMOV.NUMTRANSITEM
        INNER JOIN PCPRODUT    ON PCPRODUT.CODPROD=PCMOV.CODPROD
        INNER JOIN PCSECAO     ON PCSECAO.CODSEC=PCPRODUT.CODSEC
        INNER JOIN PCCLIENT    ON PCCLIENT.CODCLI=PCNFENT.CODFORNEC
        INNER JOIN PCPRACA     ON PCPRACA.CODPRACA=PCCLIENT.CODPRACA
        CROSS JOIN PARAMS P
    WHERE PCNFENT.DTENT BETWEEN P.DT_MES_INI AND P.DT_HOJE
      AND PCMOV.DTMOV   BETWEEN P.DT_MES_INI AND P.DT_HOJE
      AND PCNFENT.CODFILIAL IN ('{FILIAL}') AND PCMOV.CODFILIAL IN ('{FILIAL}')
      AND NVL(PCNFENT.CODFISCAL,0) IN (131,132,231,232,199,299)
      AND PCMOV.CODOPER='ED' AND PCNFENT.TIPODESCARGA IN ('6','7','T')
      AND NVL(PCNFENT.TIPOMOVGARANTIA,-1)=-1 AND NVL(PCNFENT.OBS,'X')<>'NF CANCELADA'
      AND PCMOV.DTCANCEL IS NULL AND NVL(PCNFSAID.CONDVENDA,0) NOT IN (4,8,10,13,20,98,99)
      {excl_devol}
      {filtro_devolucoes_mes}
    GROUP BY PCNFENT.CODUSURDEVOL, PCSECAO.CODSEC
),
NAO_FATURADO_SEMANA AS (
    SELECT PCUSUARI.CODUSUR AS COD_VENDEDOR, PCPRODUT.CODSEC AS COD_SECAO,
        SUM(ROUND(NVL(PCPEDI.QT,0)*(NVL(PCPEDI.PVENDA,0)+NVL(PCPEDI.VLOUTRASDESP,0)+NVL(PCPEDI.VLFRETE,0)),2)) AS VLNAO_FAT_SEMANA
    FROM PCPEDI,PCPEDC,PCPRODUT,PCFORNEC,PCSECAO,PCUSUARI,PCDEPTO,PARAMS P
    WHERE PCPEDI.NUMPED=PCPEDC.NUMPED AND PCPEDC.CODUSUR=PCUSUARI.CODUSUR
      AND PCPEDI.CODPROD=PCPRODUT.CODPROD(+) AND PCPRODUT.CODEPTO=PCDEPTO.CODEPTO(+)
      AND PCPRODUT.CODSEC=PCSECAO.CODSEC(+) AND PCPRODUT.CODFORNEC=PCFORNEC.CODFORNEC(+)
      AND PCPEDC.CODFILIAL IN ('{FILIAL}') AND PCPEDC.CONDVENDA IN (1,2,3,7,9,14,15,17,18,19,98)
      AND PCPEDC.DATA BETWEEN TO_DATE('{NF_DATA_INI}','YYYY-MM-DD') AND TO_DATE('{NF_DATA_FIM}','YYYY-MM-DD')
      AND {NF_ATIVO}
      AND PCPEDC.POSICAO<>'F' AND NVL(PCPEDI.BONIFIC,'N')='N'
      AND PCPEDC.DTCANCEL IS NULL AND PCUSUARI.CODSUPERVISOR NOT IN ('9999')
      {excl_usur}
      {filtro_nao_fat_semana}
    GROUP BY PCUSUARI.CODUSUR, PCPRODUT.CODSEC
    HAVING SUM(NVL(PCPEDI.QT,0)*(NVL(PCPEDI.PVENDA,0)+NVL(PCPEDI.VLOUTRASDESP,0)+NVL(PCPEDI.VLFRETE,0)))>0
),
NAO_FATURADO_HOJE AS (
    SELECT PCUSUARI.CODUSUR AS COD_VENDEDOR, PCPRODUT.CODSEC AS COD_SECAO,
        SUM(ROUND(NVL(PCPEDI.QT,0)*(NVL(PCPEDI.PVENDA,0)+NVL(PCPEDI.VLOUTRASDESP,0)+NVL(PCPEDI.VLFRETE,0)),2)) AS VLNAO_FAT_HOJE
    FROM PCPEDI,PCPEDC,PCPRODUT,PCFORNEC,PCSECAO,PCUSUARI,PCDEPTO,PARAMS P
    WHERE PCPEDI.NUMPED=PCPEDC.NUMPED AND PCPEDC.CODUSUR=PCUSUARI.CODUSUR
      AND PCPEDI.CODPROD=PCPRODUT.CODPROD(+) AND PCPRODUT.CODEPTO=PCDEPTO.CODEPTO(+)
      AND PCPRODUT.CODSEC=PCSECAO.CODSEC(+) AND PCPRODUT.CODFORNEC=PCFORNEC.CODFORNEC(+)
      AND PCPEDC.CODFILIAL IN ('{FILIAL}') AND PCPEDC.CONDVENDA IN (1,2,3,7,9,14,15,17,18,19,98)
      AND PCPEDC.DATA=P.DT_HOJE AND PCPEDC.POSICAO<>'F'
      AND NVL(PCPEDI.BONIFIC,'N')='N' AND PCPEDC.DTCANCEL IS NULL
      AND PCUSUARI.CODSUPERVISOR NOT IN ('9999')
      {excl_usur}
      {filtro_nao_fat_hoje}
    GROUP BY PCUSUARI.CODUSUR, PCPRODUT.CODSEC
    HAVING SUM(NVL(PCPEDI.QT,0)*(NVL(PCPEDI.PVENDA,0)+NVL(PCPEDI.VLOUTRASDESP,0)+NVL(PCPEDI.VLFRETE,0)))>0
),
FATURADO_HOJE AS (
    SELECT PCUSUARI.CODUSUR AS COD_VENDEDOR, PCSECAO.CODSEC AS COD_SECAO,
        SUM(CASE WHEN NVL(PCMOVCOMPLE.VLSUBTOTITEM,0)<>0 THEN
                DECODE(NVL(PCMOV.TIPOITEM,'N'),'I',0,NVL(PCMOVCOMPLE.VLSUBTOTITEM,0)+(DECODE(NVL(PCMOV.TIPOITEM,'N'),'I',NVL(PCMOV.QTCONT,0),0)*NVL(PCMOV.VLFRETE,0)))
            ELSE
                ROUND(DECODE(PCMOV.CODOPER,'S',NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0),'ST',NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0),'SM',NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0),0)
                *NVL(DECODE(PCNFSAID.CONDVENDA,7,NVL(PCMOV.PUNITCONT,0)-NVL(PCMOV.VLIPI,0)-(NVL(PCMOV.ST,0)+NVL(PCMOVCOMPLE.VLSTTRANSFCD,0))+NVL(PCMOV.VLFRETE,0)+NVL(PCMOV.VLOUTRASDESP,0)+NVL(PCMOV.VLFRETE_RATEIO,0)+DECODE(NVL(PCNFSAID.SOMAREPASSEOUTRASDESPNF,'N'),'N',NVL(PCMOV.VLOUTROS,0),'S',NVL(PCMOV.VLOUTROS,0)-NVL(PCMOV.VLREPASSE,0)),NVL(PCMOV.PUNIT,0)-NVL(PCMOV.VLIPI,0)-(NVL(PCMOV.ST,0)+NVL(PCMOVCOMPLE.VLSTTRANSFCD,0))+NVL(PCMOV.VLFRETE,0)+NVL(PCMOV.VLOUTRASDESP,0)+NVL(PCMOV.VLFRETE_RATEIO,0)+DECODE(NVL(PCNFSAID.SOMAREPASSEOUTRASDESPNF,'N'),'N',NVL(PCMOV.VLOUTROS,0),'S',NVL(PCMOV.VLOUTROS,0)-NVL(PCMOV.VLREPASSE,0))),0),2)
                +ROUND(NVL(PCMOV.QT,0)*DECODE(PCNFSAID.CONDVENDA,5,0,6,0,11,0,12,0,DECODE(PCMOV.CODOPER,'SB',0,NVL(PCMOV.ST,0)+NVL(PCMOVCOMPLE.VLSTTRANSFCD,0))),2)
                +ROUND(NVL(PCMOV.QT,0)*DECODE(PCNFSAID.CONDVENDA,5,0,6,0,11,0,12,0,DECODE(PCMOV.CODOPER,'SB',0,NVL(PCMOV.VLIPI,0))),2)
        END) AS VLFATURADO_HOJE
    FROM PCNFSAID
        INNER JOIN PCMOV       ON PCMOV.NUMTRANSVENDA=PCNFSAID.NUMTRANSVENDA AND PCMOV.CODFILIAL=PCNFSAID.CODFILIAL
        LEFT  JOIN PCMOVCOMPLE ON PCMOVCOMPLE.NUMTRANSITEM=PCMOV.NUMTRANSITEM
        INNER JOIN PCPRODUT    ON PCPRODUT.CODPROD=PCMOV.CODPROD
        INNER JOIN PCUSUARI    ON PCUSUARI.CODUSUR=PCNFSAID.CODUSUR
        INNER JOIN PCSUPERV    ON PCSUPERV.CODSUPERVISOR=NVL(PCNFSAID.CODSUPERVISOR,PCUSUARI.CODSUPERVISOR)
        LEFT  JOIN PCSECAO     ON PCSECAO.CODSEC=PCPRODUT.CODSEC
        CROSS JOIN PARAMS P
    WHERE PCMOV.DTMOV=P.DT_HOJE AND PCNFSAID.DTSAIDA=P.DT_HOJE
      AND PCMOV.CODFILIAL IN ('{FILIAL}') AND PCNFSAID.CODFILIAL IN ('{FILIAL}')
      AND PCMOV.CODOPER NOT IN ('SR','SO')
      AND NVL(PCNFSAID.TIPOVENDA,'X') NOT IN ('SR','DF')
      AND PCNFSAID.CODFISCAL NOT IN (522,622,722,532,632,732)
      AND PCNFSAID.CONDVENDA NOT IN (4,8,10,13,20,98,99)
      AND PCNFSAID.DTCANCEL IS NULL
      {excl_usur}
      {filtro_fat_hoje}
    GROUP BY PCUSUARI.CODUSUR, PCSECAO.CODSEC
)
{select_final}
""".replace("{FILIAL}", FILIAL)

# ─────────────────────────────────────────────────────────────────────────────
# SELECTs finais
# ─────────────────────────────────────────────────────────────────────────────
SELECT_LINHAS = """
SELECT
    V.COD_VENDEDOR, V.NOME_VENDEDOR, V.COD_SUPERVISOR, V.NOME_SUPERVISOR, V.COD_SECAO, V.SECAO,
    ROUND(V.VLVENDA-NVL(D.VLDEVOLUCAO,0),2)                                                              AS VALOR_FATURADO_SECAO,
    ROUND(((V.VLVENDA-NVL(D.VLDEVOLUCAO,0))/NULLIF(P.DIAS_UTEIS_CONSULTA,0))*P.DIAS_UTEIS_MES_ATUAL*1.05,2) AS VALOR_META_SECAO,
    ROUND(NVL(VM.VLVENDA_MES,0)-NVL(DM.VLDEVOLUCAO_MES,0),2)                                            AS FATURADO_MES_PURO,
    ROUND(NVL(NS.VLNAO_FAT_SEMANA,0),2)                                                                  AS NAO_FATURADO_SEMANA,
    ROUND(NVL(VM.VLVENDA_MES,0)-NVL(DM.VLDEVOLUCAO_MES,0)+NVL(NS.VLNAO_FAT_SEMANA,0),2)                AS VALOR_FATURADO_MES_ATUAL,
    ROUND(ROUND(((V.VLVENDA-NVL(D.VLDEVOLUCAO,0))/NULLIF(P.DIAS_UTEIS_CONSULTA,0))*P.DIAS_UTEIS_MES_ATUAL*1.05,2)
          -ROUND(NVL(VM.VLVENDA_MES,0)-NVL(DM.VLDEVOLUCAO_MES,0)+NVL(NS.VLNAO_FAT_SEMANA,0),2),2)      AS RESTA_A_FAZER,
    ROUND((ROUND(((V.VLVENDA-NVL(D.VLDEVOLUCAO,0))/NULLIF(P.DIAS_UTEIS_CONSULTA,0))*P.DIAS_UTEIS_MES_ATUAL*1.05,2)
           -ROUND(NVL(VM.VLVENDA_MES,0)-NVL(DM.VLDEVOLUCAO_MES,0)+NVL(NS.VLNAO_FAT_SEMANA,0),2))
          /NULLIF(P.DIAS_UTEIS_MES_ATUAL-P.DIAS_UTEIS_DECORRIDOS,0),2)                                   AS NECESSIDADE_DIA,
    ROUND(NVL(NH.VLNAO_FAT_HOJE,0),2)                                                                    AS NAO_FATURADO_HOJE,
    ROUND(NVL(FH.VLFATURADO_HOJE,0),2)                                                                   AS FATURADO_HOJE,
    ROUND(NVL(NH.VLNAO_FAT_HOJE,0)+NVL(FH.VLFATURADO_HOJE,0),2)                                        AS REALIZADO_DIA,
    ROUND(((NVL(VM.VLVENDA_MES,0)-NVL(DM.VLDEVOLUCAO_MES,0)+NVL(NS.VLNAO_FAT_SEMANA,0))/NULLIF(P.DIAS_UTEIS_DECORRIDOS,0)*P.DIAS_UTEIS_MES_ATUAL)
          /NULLIF(ROUND(((V.VLVENDA-NVL(D.VLDEVOLUCAO,0))/NULLIF(P.DIAS_UTEIS_CONSULTA,0))*P.DIAS_UTEIS_MES_ATUAL*1.05,2),0)*100,2) AS TENDENCIA_PCT,
    P.DIAS_UTEIS_CONSULTA AS DIAS_UTEIS_CONSULTADOS, P.DIAS_UTEIS_MES_ATUAL, P.DIAS_UTEIS_DECORRIDOS
FROM VENDAS V
    LEFT JOIN DEVOLUCOES          D  ON D.COD_VENDEDOR=V.COD_VENDEDOR  AND D.COD_SECAO=V.COD_SECAO
    LEFT JOIN VENDAS_MES          VM ON VM.COD_VENDEDOR=V.COD_VENDEDOR AND VM.COD_SECAO=V.COD_SECAO
    LEFT JOIN DEVOLUCOES_MES      DM ON DM.COD_VENDEDOR=V.COD_VENDEDOR AND DM.COD_SECAO=V.COD_SECAO
    LEFT JOIN NAO_FATURADO_SEMANA NS ON NS.COD_VENDEDOR=V.COD_VENDEDOR AND NS.COD_SECAO=V.COD_SECAO
    LEFT JOIN NAO_FATURADO_HOJE   NH ON NH.COD_VENDEDOR=V.COD_VENDEDOR AND NH.COD_SECAO=V.COD_SECAO
    LEFT JOIN FATURADO_HOJE       FH ON FH.COD_VENDEDOR=V.COD_VENDEDOR AND FH.COD_SECAO=V.COD_SECAO
    CROSS JOIN PARAMS P
ORDER BY V.COD_VENDEDOR, V.COD_SECAO
"""

_SELECT_AGG_TMPL = """
SELECT
    {group_cols},
    SUM(ROUND(V.VLVENDA-NVL(D.VLDEVOLUCAO,0),2))                                                                            AS VALOR_FATURADO_SECAO,
    SUM(ROUND(((V.VLVENDA-NVL(D.VLDEVOLUCAO,0))/NULLIF(P.DIAS_UTEIS_CONSULTA,0))*P.DIAS_UTEIS_MES_ATUAL*1.05,2))           AS VALOR_META_SECAO,
    SUM(ROUND(NVL(VM.VLVENDA_MES,0)-NVL(DM.VLDEVOLUCAO_MES,0),2))                                                          AS FATURADO_MES_PURO,
    SUM(ROUND(NVL(NS.VLNAO_FAT_SEMANA,0),2))                                                                                AS NAO_FATURADO_SEMANA,
    SUM(ROUND(NVL(VM.VLVENDA_MES,0)-NVL(DM.VLDEVOLUCAO_MES,0)+NVL(NS.VLNAO_FAT_SEMANA,0),2))                              AS VALOR_FATURADO_MES_ATUAL,
    SUM(ROUND(ROUND(((V.VLVENDA-NVL(D.VLDEVOLUCAO,0))/NULLIF(P.DIAS_UTEIS_CONSULTA,0))*P.DIAS_UTEIS_MES_ATUAL*1.05,2)-ROUND(NVL(VM.VLVENDA_MES,0)-NVL(DM.VLDEVOLUCAO_MES,0)+NVL(NS.VLNAO_FAT_SEMANA,0),2),2)) AS RESTA_A_FAZER,
    ROUND((SUM(ROUND(((V.VLVENDA-NVL(D.VLDEVOLUCAO,0))/NULLIF(P.DIAS_UTEIS_CONSULTA,0))*P.DIAS_UTEIS_MES_ATUAL*1.05,2))-SUM(ROUND(NVL(VM.VLVENDA_MES,0)-NVL(DM.VLDEVOLUCAO_MES,0)+NVL(NS.VLNAO_FAT_SEMANA,0),2)))/NULLIF(MAX(P.DIAS_UTEIS_MES_ATUAL)-MAX(P.DIAS_UTEIS_DECORRIDOS),0),2) AS NECESSIDADE_DIA,
    SUM(ROUND(NVL(NH.VLNAO_FAT_HOJE,0),2))                                                                                  AS NAO_FATURADO_HOJE,
    SUM(ROUND(NVL(FH.VLFATURADO_HOJE,0),2))                                                                                 AS FATURADO_HOJE,
    SUM(ROUND(NVL(NH.VLNAO_FAT_HOJE,0)+NVL(FH.VLFATURADO_HOJE,0),2))                                                      AS REALIZADO_DIA,
    ROUND((SUM(NVL(VM.VLVENDA_MES,0)-NVL(DM.VLDEVOLUCAO_MES,0)+NVL(NS.VLNAO_FAT_SEMANA,0))/NULLIF(MAX(P.DIAS_UTEIS_DECORRIDOS),0)*MAX(P.DIAS_UTEIS_MES_ATUAL))/NULLIF(SUM(ROUND(((V.VLVENDA-NVL(D.VLDEVOLUCAO,0))/NULLIF(P.DIAS_UTEIS_CONSULTA,0))*P.DIAS_UTEIS_MES_ATUAL*1.05,2)),0)*100,2) AS TENDENCIA_PCT,
    MAX(P.DIAS_UTEIS_CONSULTA) AS DIAS_UTEIS_CONSULTADOS, MAX(P.DIAS_UTEIS_MES_ATUAL) AS DIAS_UTEIS_MES_ATUAL, MAX(P.DIAS_UTEIS_DECORRIDOS) AS DIAS_UTEIS_DECORRIDOS
FROM VENDAS V
    LEFT JOIN DEVOLUCOES          D  ON D.COD_VENDEDOR=V.COD_VENDEDOR  AND D.COD_SECAO=V.COD_SECAO
    LEFT JOIN VENDAS_MES          VM ON VM.COD_VENDEDOR=V.COD_VENDEDOR AND VM.COD_SECAO=V.COD_SECAO
    LEFT JOIN DEVOLUCOES_MES      DM ON DM.COD_VENDEDOR=V.COD_VENDEDOR AND DM.COD_SECAO=V.COD_SECAO
    LEFT JOIN NAO_FATURADO_SEMANA NS ON NS.COD_VENDEDOR=V.COD_VENDEDOR AND NS.COD_SECAO=V.COD_SECAO
    LEFT JOIN NAO_FATURADO_HOJE   NH ON NH.COD_VENDEDOR=V.COD_VENDEDOR AND NH.COD_SECAO=V.COD_SECAO
    LEFT JOIN FATURADO_HOJE       FH ON FH.COD_VENDEDOR=V.COD_VENDEDOR AND FH.COD_SECAO=V.COD_SECAO
    CROSS JOIN PARAMS P
GROUP BY {group_by_cols}
ORDER BY {order_cols}
"""

SELECT_SUPERVISOR = _SELECT_AGG_TMPL.format(
    group_cols    = "V.COD_SUPERVISOR, V.NOME_SUPERVISOR, V.COD_SECAO, V.SECAO",
    group_by_cols = "V.COD_SUPERVISOR, V.NOME_SUPERVISOR, V.COD_SECAO, V.SECAO",
    order_cols    = "V.COD_SECAO",
)
SELECT_GERENCIAL = _SELECT_AGG_TMPL.format(
    group_cols    = "V.COD_SECAO, V.SECAO",
    group_by_cols = "V.COD_SECAO, V.SECAO",
    order_cols    = "V.COD_SECAO",
)

# ── Ranking: agrega todas as seções por vendedor, ordena por tendência ────────
SELECT_RANKING = """
SELECT
    V.COD_VENDEDOR,
    V.NOME_VENDEDOR,
    V.COD_SUPERVISOR,
    V.NOME_SUPERVISOR,
    SUM(ROUND(V.VLVENDA-NVL(D.VLDEVOLUCAO,0),2))                                                                            AS VALOR_FATURADO_SECAO,
    SUM(ROUND(((V.VLVENDA-NVL(D.VLDEVOLUCAO,0))/NULLIF(P.DIAS_UTEIS_CONSULTA,0))*P.DIAS_UTEIS_MES_ATUAL*1.05,2))           AS VALOR_META_SECAO,
    SUM(ROUND(NVL(VM.VLVENDA_MES,0)-NVL(DM.VLDEVOLUCAO_MES,0),2))                                                          AS FATURADO_MES_PURO,
    SUM(ROUND(NVL(NS.VLNAO_FAT_SEMANA,0),2))                                                                                AS NAO_FATURADO_SEMANA,
    SUM(ROUND(NVL(VM.VLVENDA_MES,0)-NVL(DM.VLDEVOLUCAO_MES,0)+NVL(NS.VLNAO_FAT_SEMANA,0),2))                              AS VALOR_FATURADO_MES_ATUAL,
    SUM(ROUND(ROUND(((V.VLVENDA-NVL(D.VLDEVOLUCAO,0))/NULLIF(P.DIAS_UTEIS_CONSULTA,0))*P.DIAS_UTEIS_MES_ATUAL*1.05,2)-ROUND(NVL(VM.VLVENDA_MES,0)-NVL(DM.VLDEVOLUCAO_MES,0)+NVL(NS.VLNAO_FAT_SEMANA,0),2),2)) AS RESTA_A_FAZER,
    ROUND((SUM(ROUND(((V.VLVENDA-NVL(D.VLDEVOLUCAO,0))/NULLIF(P.DIAS_UTEIS_CONSULTA,0))*P.DIAS_UTEIS_MES_ATUAL*1.05,2))-SUM(ROUND(NVL(VM.VLVENDA_MES,0)-NVL(DM.VLDEVOLUCAO_MES,0)+NVL(NS.VLNAO_FAT_SEMANA,0),2)))/NULLIF(MAX(P.DIAS_UTEIS_MES_ATUAL)-MAX(P.DIAS_UTEIS_DECORRIDOS),0),2) AS NECESSIDADE_DIA,
    SUM(ROUND(NVL(NH.VLNAO_FAT_HOJE,0),2))                                                                                  AS NAO_FATURADO_HOJE,
    SUM(ROUND(NVL(FH.VLFATURADO_HOJE,0),2))                                                                                 AS FATURADO_HOJE,
    SUM(ROUND(NVL(NH.VLNAO_FAT_HOJE,0)+NVL(FH.VLFATURADO_HOJE,0),2))                                                      AS REALIZADO_DIA,
    ROUND((SUM(NVL(VM.VLVENDA_MES,0)-NVL(DM.VLDEVOLUCAO_MES,0)+NVL(NS.VLNAO_FAT_SEMANA,0))/NULLIF(MAX(P.DIAS_UTEIS_DECORRIDOS),0)*MAX(P.DIAS_UTEIS_MES_ATUAL))/NULLIF(SUM(ROUND(((V.VLVENDA-NVL(D.VLDEVOLUCAO,0))/NULLIF(P.DIAS_UTEIS_CONSULTA,0))*P.DIAS_UTEIS_MES_ATUAL*1.05,2)),0)*100,2) AS TENDENCIA_PCT,
    MAX(P.DIAS_UTEIS_CONSULTA) AS DIAS_UTEIS_CONSULTADOS, MAX(P.DIAS_UTEIS_MES_ATUAL) AS DIAS_UTEIS_MES_ATUAL, MAX(P.DIAS_UTEIS_DECORRIDOS) AS DIAS_UTEIS_DECORRIDOS
FROM VENDAS V
    LEFT JOIN DEVOLUCOES          D  ON D.COD_VENDEDOR=V.COD_VENDEDOR  AND D.COD_SECAO=V.COD_SECAO
    LEFT JOIN VENDAS_MES          VM ON VM.COD_VENDEDOR=V.COD_VENDEDOR AND VM.COD_SECAO=V.COD_SECAO
    LEFT JOIN DEVOLUCOES_MES      DM ON DM.COD_VENDEDOR=V.COD_VENDEDOR AND DM.COD_SECAO=V.COD_SECAO
    LEFT JOIN NAO_FATURADO_SEMANA NS ON NS.COD_VENDEDOR=V.COD_VENDEDOR AND NS.COD_SECAO=V.COD_SECAO
    LEFT JOIN NAO_FATURADO_HOJE   NH ON NH.COD_VENDEDOR=V.COD_VENDEDOR AND NH.COD_SECAO=V.COD_SECAO
    LEFT JOIN FATURADO_HOJE       FH ON FH.COD_VENDEDOR=V.COD_VENDEDOR AND FH.COD_SECAO=V.COD_SECAO
    CROSS JOIN PARAMS P
GROUP BY V.COD_VENDEDOR, V.NOME_VENDEDOR, V.COD_SUPERVISOR, V.NOME_SUPERVISOR
ORDER BY TENDENCIA_PCT DESC NULLS LAST
"""


def build_ranking_query(filtro_supervisor: Optional[int] = None,
                        date_ref: Optional[str] = None) -> tuple:
    """Retorna SQL + params para o ranking de vendedores (todas as seções somadas)."""
    from database import parse_data
    excl_usur  = "AND PCUSUARI.CODUSUR NOT IN (2,10,160,180)"
    excl_devol = "AND PCNFENT.CODUSURDEVOL NOT IN (2,10,160,180)"

    if filtro_supervisor is not None:
        fv  = "AND NVL(PCNFSAID.CODSUPERVISOR,PCUSUARI.CODSUPERVISOR) = :p1"
        fd  = "AND NVL(PCNFSAID.CODSUPERVISOR,PCUSUARI.CODSUPERVISOR) = :p2"
        fvm = "AND NVL(PCNFSAID.CODSUPERVISOR,PCUSUARI.CODSUPERVISOR) = :p3"
        fdm = "AND NVL(PCNFSAID.CODSUPERVISOR,PCUSUARI.CODSUPERVISOR) = :p4"
        fns = "AND PCUSUARI.CODSUPERVISOR = :p5"
        fnh = "AND PCUSUARI.CODSUPERVISOR = :p6"
        ffh = "AND PCUSUARI.CODSUPERVISOR = :p7"
        params = [filtro_supervisor] * 7
    else:
        fv = fd = fvm = fdm = fns = fnh = ffh = ""
        params = []

    dr = date_ref or parse_data(None)

    from datetime import date, timedelta
    dr_date  = date.fromisoformat(dr)
    hoje     = date.today()
    mes_atual = (dr_date.year == hoje.year and dr_date.month == hoje.month)

    if mes_atual:
        mes_ini      = dr_date.replace(day=1)
        dias_ate_dom = (dr_date.weekday() + 1) % 7
        ultimo_dom   = dr_date - timedelta(days=dias_ate_dom)
        nf_ini       = max(mes_ini, ultimo_dom)
        nf_fim       = dr_date - timedelta(days=1)
        nf_ativo     = "1=1"
    else:
        nf_ini = nf_fim = dr_date
        nf_ativo = "1=0"

    sql = (BASE_SQL
           .replace("{DATE_REF}",    dr)
           .replace("{NF_DATA_INI}", nf_ini.strftime("%Y-%m-%d"))
           .replace("{NF_DATA_FIM}", nf_fim.strftime("%Y-%m-%d"))
           .replace("{NF_ATIVO}",    nf_ativo)
           .format(
               excl_usur=excl_usur,       excl_devol=excl_devol,
               filtro_vendas=fv,          filtro_devolucoes=fd,
               filtro_vendas_mes=fvm,     filtro_devolucoes_mes=fdm,
               filtro_nao_fat_semana=fns, filtro_nao_fat_hoje=fnh,
               filtro_fat_hoje=ffh,       select_final=SELECT_RANKING,
           ))
    return sql, params


# ─────────────────────────────────────────────────────────────────────────────
# build_query — monta SQL + params conforme o modo
# ─────────────────────────────────────────────────────────────────────────────
def build_query(modo: str, filtro_id: Optional[int] = None, date_ref: Optional[str] = None) -> tuple:
    from database import parse_data
    excl_usur  = "" if modo == "gerencial" else "AND PCUSUARI.CODUSUR NOT IN (2,10,160,180)"
    excl_devol = "" if modo == "gerencial" else "AND PCNFENT.CODUSURDEVOL NOT IN (2,10,160,180)"

    params: list = []

    if modo == "gerencial":
        fv = fd = fvm = fdm = fns = fnh = ffh = ""
        sel = SELECT_GERENCIAL
    elif modo == "vendedor" and filtro_id is not None:
        fv, fd, fvm, fdm, fns, fnh, ffh = (
            "AND PCUSUARI.CODUSUR = :p1",
            "AND PCNFENT.CODUSURDEVOL = :p2",
            "AND PCUSUARI.CODUSUR = :p3",
            "AND PCNFENT.CODUSURDEVOL = :p4",
            "AND PCUSUARI.CODUSUR = :p5",
            "AND PCUSUARI.CODUSUR = :p6",
            "AND PCUSUARI.CODUSUR = :p7",
        )
        params = [filtro_id] * 7
        sel = SELECT_LINHAS
    elif modo in ("equipe", "supervisor") and filtro_id is not None:
        fv, fd, fvm, fdm, fns, fnh, ffh = (
            "AND NVL(PCNFSAID.CODSUPERVISOR,PCUSUARI.CODSUPERVISOR) = :p1",
            "AND NVL(PCNFSAID.CODSUPERVISOR,PCUSUARI.CODSUPERVISOR) = :p2",
            "AND NVL(PCNFSAID.CODSUPERVISOR,PCUSUARI.CODSUPERVISOR) = :p3",
            "AND NVL(PCNFSAID.CODSUPERVISOR,PCUSUARI.CODSUPERVISOR) = :p4",
            "AND PCUSUARI.CODSUPERVISOR = :p5",
            "AND PCUSUARI.CODSUPERVISOR = :p6",
            "AND PCUSUARI.CODSUPERVISOR = :p7",
        )
        params = [filtro_id] * 7
        sel = SELECT_LINHAS if modo == "equipe" else SELECT_SUPERVISOR
    else:  # todos
        fv = fd = fvm = fdm = fns = fnh = ffh = ""
        sel = SELECT_LINHAS

    dr = date_ref or parse_data(None)

    # Calcula período do NF e verifica se é mês atual — tudo em Python, sem SYSDATE no Oracle
    from datetime import date, timedelta
    dr_date = date.fromisoformat(dr)
    hoje    = date.today()

    mes_atual = (dr_date.year == hoje.year and dr_date.month == hoje.month)

    if mes_atual:
        # Início do mês atual
        mes_ini   = dr_date.replace(day=1)
        # weekday(): Monday=0, Sunday=6
        dias_ate_dom = (dr_date.weekday() + 1) % 7  # dias desde último domingo
        ultimo_dom   = dr_date - timedelta(days=dias_ate_dom)
        nf_ini = max(mes_ini, ultimo_dom)            # último domingo (igual a DT_SEMANA_INI do 1464)
        nf_fim = dr_date - timedelta(days=1)         # ontem (igual a DT_ONTEM do 1464)
        nf_ativo = "1=1"
    else:
        # Mês passado: NF zerado
        nf_ini   = dr_date
        nf_fim   = dr_date
        nf_ativo = "1=0"

    nf_ini_str = nf_ini.strftime("%Y-%m-%d")
    nf_fim_str = nf_fim.strftime("%Y-%m-%d")

    sql = (BASE_SQL
           .replace("{DATE_REF}",    dr)
           .replace("{NF_DATA_INI}", nf_ini_str)
           .replace("{NF_DATA_FIM}", nf_fim_str)
           .replace("{NF_ATIVO}",    nf_ativo)
           .format(
               excl_usur=excl_usur,       excl_devol=excl_devol,
               filtro_vendas=fv,          filtro_devolucoes=fd,
               filtro_vendas_mes=fvm,     filtro_devolucoes_mes=fdm,
               filtro_nao_fat_semana=fns, filtro_nao_fat_hoje=fnh,
               filtro_fat_hoje=ffh,       select_final=sel,
           ))
    return sql, params